:toc: 
:icons: font
:source-highlighter: prettify
:project_id: draft-gs-template

image::https://push-to.cfapps.io/ui/assets/images/Push-to-Pivotal-Light.svg["PWS"]

This guide walks you through the process of adding a Push-to-PWS button to your repo and testing the functionality.

== What you'll build

It's not what YOU will build, but what you enable users to build.  This new functionality lets users simply push a button to spin up your application on Pivotal Web Services.

image::https://push-to.cfapps.io/ui/assets/images/Push-to-Pivotal-Light.svg["PWS,200]



== What you'll need

* A Git Repository you want to add this functionality to.  This guide uses https://github.com/spring-cloud-services-samples/fortune-teller  as an example.

* A Pivotal Web Services account -- for testing purposes. You can sign up at https://run.pivotal.io[here].


[[initial]]
== Fork/Clone the repo

We wil need to clone our repo, so that we can make changes to it.  If this is your personal repo, you can clone it immediately, but for this example we are using the Fortune Teller app, so we will need to fork it first and then clone it.
----
git clone https://github.com/<username>/fortune-teller
----


== Create push-to-pws directory

The application and services manifest files that get created will be stored here.

----
cd fortune-teller
mkdir push-to-pws
----

This example repo already has our application manifest created, but it needs to be renamed to manifest.yml.  This repo also has a manifest-pcf.yml that can be deleted.
----
mv manifest-pws.yml push-to-pws/manifest.yml
----


== Manifest Changes

The push-to-pws functioanlity requires that any user-accessible application/service be listed first in the manifest.  In the fortune-teller manifest we have 2 applications defined: a UI and a service.
----
---
applications:
- name: fortunes
  memory: 1024M
  random-route: true
  path: fortune-teller-fortune-service/target/fortune-teller-fortune-service-0.0.1-SNAPSHOT.jar
  instances: 1
  services:
  - fortunes-db
  - fortunes-config-server
  - fortunes-service-registry
- name: fortune-ui
  memory: 1024M
  random-route: true
  path: fortune-teller-ui/target/fortune-teller-ui-0.0.1-SNAPSHOT.jar
  instances: 1
  services:
  - fortunes-config-server
  - fortunes-service-registry
  - fortunes-circuit-breaker-dashboard
----

Since, the UI is the user-accessible application it should be listed first, so the manifest should be changed to look like this:
----
---
applications:
- name: fortune-ui
  memory: 1024M
  random-route: true
  path: fortune-teller-ui/target/fortune-teller-ui-0.0.1-SNAPSHOT.jar
  instances: 1
  services:
  - fortunes-config-server
  - fortunes-service-registry
  - fortunes-circuit-breaker-dashboard
- name: fortunes
  memory: 1024M
  random-route: true
  path: fortune-teller-fortune-service/target/fortune-teller-fortune-service-0.0.1-SNAPSHOT.jar
  instances: 1
  services:
  - fortunes-db
  - fortunes-config-server
  - fortunes-service-registry
----

== Service Definition File
The Service Definition file (services.yml) is the file that will define any backing services that are required for the application when running on PWS.  This file is defined in the same format as the definitions in the continuous delivery tool, Spinnaker.
----
service_name:
service:
service_plan:
---
service_name:
service:
service_plan:
---
----

The services required for fortune-teller can be found in the manifest.yml file

* fortunes-config-server

* fortunes-service-registry

* fortunes-circuit-breaker-dashboard

* fortunes-db


These should be added to the service.yml file
----
service_name: fortunes-config-server
service: 
service_plan: 
---
service_name: fortunes-service-registry
service: 
service_plan: 
---
service_name: fortunes-circuit-breaker-dashboard
service: 
service_plan: 
---
service_name: fortunes-db
service: 
service_plan: 
----

Next step will be to fill in the details for this file.  These can ge obtained from looking at the PWS CF Marketplace.  The easiest way to get this info is to login to your test PWS instance via the CLI:

----
cf login -a api.run.pivotal.io
cf m
cf m | grep SQL
cf m | grep dashboard
cf m | grep registry
cf m | config
----

Take the info from these commands and add it to the services.yml file
----
service_name: fortunes-config-server
service: p-config-server
service_plan: trial
---
service_name: fortunes-service-registry
service: p-service-registry
service_plan: trial
---
service_name: fortunes-circuit-breaker-dashboard
service: p-circuit-breaker-dashboard
service_plan: trial
---
service_name: fortunes-db
service: cleardb
service_plan: spark
----

For this particular example, the configuration server needs to be configured a bit more.  You can point it at a specific repo directory to grab it's configuration.  The details of this can be found https://docs.run.pivotal.io/spring-cloud-services/config-server/configuring-with-git.html[in the Spring Cloud Config Server on PWS docs]

----
service_name: fortunes-config-server
service: p-config-server
service_plan: trial
parameters:
  git:
    uri: https://github.com/dbbaskette/fortune-teller
    searchPaths: configuration
---
service_name: fortunes-service-registry
service: p-service-registry
service_plan: trial
---
service_name: fortunes-circuit-breaker-dashboard
service: p-circuit-breaker-dashboard
service_plan: trial
---
service_name: fortunes-db
service: cleardb
service_plan: spark
----

== Create the Push-to-PWS Button

To create the Push-to-PWS Button browse to: https://push-to.cfapps.io/ui/create-button
Input the path to your repo and hit CREATE PUSH BUTTON.

Copy the HTML snippet out and put in your README.md file in the repo.

== Commit and Push Repo changes
----
git add .
git commit -m "Push to PWS"
git push
----

== Testing
* Login to your PWS account
* Create a new space to deploy your app for testing.
* Bring up your Repo and Click on the new Push-to-PWS button

The repo should be pre-poulated, but you will need to select the space you just create.  Then click build and push app.  An output terminal should dislay while the app builds and deploys.

== Summary

Congratulations! You've just deployed your first Push-to-PWS button.


